import React, {useEffect, useMemo, useState} from 'react';
import { createRoot } from 'react-dom/client';
import { createClient } from '@supabase/supabase-js';
import './style.css';

const URL = import.meta.env.VITE_SUPABASE_URL;
const KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;
const supabase = URL && KEY ? createClient(URL, KEY) : null;
const jobs = ['Accounts','Payroll','VAT','VAT3','VIES','Bookkeeping','CRO Filing','Revenue Registration','File / Document Sorting','Meeting','Training','Administration','Client Communication','Other'];

function csvDownload(filename, rows){
  const csv = rows.map(r => r.map(v => `"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');
  const blob = new Blob([csv], {type:'text/csv;charset=utf-8;'}); const a=document.createElement('a');
  a.href=URL.createObjectURL(blob); a.download=filename; a.click(); URL.revokeObjectURL(a.href);
}
function App(){
 const [session,setSession]=useState(null), [loading,setLoading]=useState(true), [email,setEmail]=useState(''), [password,setPassword]=useState('');
 const [tab,setTab]=useState('entry'), [entries,setEntries]=useState([]), [clients,setClients]=useState([]), [profile,setProfile]=useState(null);
 const [form,setForm]=useState({date:new Date().toISOString().slice(0,10),client:'',job:'Accounts',hours:'',details:'',billable:true});
 useEffect(()=>{ if(!supabase){setLoading(false);return;} supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)}); const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return()=>subscription.unsubscribe();},[]);
 useEffect(()=>{ if(session) loadAll();},[session]);
 async function loadAll(){ const uid=session.user.id; const p=await supabase.from('profiles').select('*').eq('id',uid).single(); setProfile(p.data); const c=await supabase.from('clients').select('*').order('name'); setClients(c.data||[]); const e=await supabase.from('time_entries').select('*, clients(name), profiles(full_name,email)').order('date',{ascending:false}); setEntries(e.data||[]); }
 async function signIn(e){e.preventDefault(); setLoading(true); const {error}= await supabase.auth.signInWithPassword({email,password}); setLoading(false); if(error) alert(error.message);}
 async function addEntry(e){ e.preventDefault(); const clientName=form.client.trim(); if(!clientName||!form.hours) return alert('Please enter client and hours'); let client=clients.find(c=>c.name.toLowerCase()===clientName.toLowerCase()); if(!client){ const r=await supabase.from('clients').insert({name:clientName}).select().single(); client=r.data; }
 const {error}=await supabase.from('time_entries').insert({date:form.date,client_id:client.id,job_name:form.job,hours:Number(form.hours),details:form.details,billable:form.billable,staff_id:session.user.id}); if(error) return alert(error.message); setForm({...form,client:'',hours:'',details:''}); loadAll(); }
 const visibleEntries = useMemo(()=> profile?.role==='staff' ? entries.filter(e=>e.staff_id===session?.user?.id) : entries, [entries,profile,session]);
 const staffSummary = useMemo(()=>{const m={}; visibleEntries.forEach(e=>{const n=e.profiles?.full_name||e.profiles?.email||'Unknown'; m[n]??={name:n,hours:0,count:0}; m[n].hours+=Number(e.hours); m[n].count++;}); return Object.values(m)},[visibleEntries]);
 const clientSummary = useMemo(()=>{const m={}; visibleEntries.forEach(e=>{const n=e.clients?.name||'Unknown'; m[n]??={name:n,hours:0,jobs:{},staff:new Set()}; m[n].hours+=Number(e.hours); m[n].jobs[e.job_name]=(m[n].jobs[e.job_name]||0)+Number(e.hours); m[n].staff.add(e.profiles?.full_name||e.profiles?.email||'Unknown')}); return Object.values(m)},[visibleEntries]);
 if(loading) return <div className="center">Loading...</div>;
 if(!supabase) return <div className="setup"><h1>PTB Time Management System</h1><p>Environment variables are missing. Add these in Vercel → Settings → Environment Variables, then redeploy:</p><code>VITE_SUPABASE_URL</code><code>VITE_SUPABASE_ANON_KEY</code></div>;
 if(!session) return <div className="login"><form onSubmit={signIn}><h1>PTB Time Management</h1><p>Internal staff login</p><input placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} /><input placeholder="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)} /><button>Login</button></form></div>;
 return <div><header><h1>PTB Time Management</h1><span>{profile?.full_name || session.user.email} · {profile?.role || 'staff'}</span><button onClick={()=>supabase.auth.signOut()}>Logout</button></header><nav>{['entry','staff','client','records'].map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)}>{t==='entry'?'Time Entry':t==='staff'?'Staff Summary':t==='client'?'Client Summary':'Records'}</button>)}</nav>
 <main>{tab==='entry'&&<section className="card"><h2>Add Time Entry</h2><form className="grid" onSubmit={addEntry}><label>Date<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>Client<input list="clientlist" value={form.client} onChange={e=>setForm({...form,client:e.target.value})} placeholder="Search or add client"/><datalist id="clientlist">{clients.map(c=><option key={c.id} value={c.name}/>)}</datalist></label><label>Job<select value={form.job} onChange={e=>setForm({...form,job:e.target.value})}>{jobs.map(j=><option>{j}</option>)}</select></label><label>Hours<input type="number" step="0.25" value={form.hours} onChange={e=>setForm({...form,hours:e.target.value})} placeholder="e.g. 1.5"/></label><label>Billable<select value={form.billable?'yes':'no'} onChange={e=>setForm({...form,billable:e.target.value==='yes'})}><option value="yes">Billable</option><option value="no">Non-billable</option></select></label><label className="wide">Work Details<textarea value={form.details} onChange={e=>setForm({...form,details:e.target.value})}/></label><button className="wide">Save Entry</button></form></section>}
 {tab==='staff'&&<section className="card"><h2>Staff Summary</h2><button onClick={()=>window.print()}>Print / Save PDF</button><button onClick={()=>csvDownload('staff-summary.csv',[['Staff','Hours','Entries'],...staffSummary.map(s=>[s.name,s.hours,s.count])])}>CSV</button><table><thead><tr><th>Staff</th><th>Total Hours</th><th>Entries</th></tr></thead><tbody>{staffSummary.map(s=><tr><td>{s.name}</td><td>{s.hours.toFixed(2)}</td><td>{s.count}</td></tr>)}</tbody></table></section>}
 {tab==='client'&&<section className="card"><h2>Client Summary</h2><button onClick={()=>window.print()}>Print / Save PDF</button><button onClick={()=>csvDownload('client-summary.csv',[['Client','Hours','Staff','Jobs'],...clientSummary.map(c=>[c.name,c.hours,[...c.staff].join('; '),Object.entries(c.jobs).map(([k,v])=>`${k}: ${v}`).join('; ')])])}>CSV</button><table><thead><tr><th>Client</th><th>Total Hours</th><th>Staff</th><th>Jobs</th></tr></thead><tbody>{clientSummary.map(c=><tr><td>{c.name}</td><td>{c.hours.toFixed(2)}</td><td>{[...c.staff].join(', ')}</td><td>{Object.entries(c.jobs).map(([k,v])=><div>{k}: {v.toFixed(2)}h</div>)}</td></tr>)}</tbody></table></section>}
 {tab==='records'&&<section className="card"><h2>All Records</h2><button onClick={()=>csvDownload('time-records.csv',[['Date','Staff','Client','Job','Hours','Billable','Details'],...visibleEntries.map(e=>[e.date,e.profiles?.full_name||e.profiles?.email,e.clients?.name,e.job_name,e.hours,e.billable?'Yes':'No',e.details])])}>CSV</button><table><thead><tr><th>Date</th><th>Staff</th><th>Client</th><th>Job</th><th>Hours</th><th>Details</th></tr></thead><tbody>{visibleEntries.map(e=><tr><td>{e.date}</td><td>{e.profiles?.full_name||e.profiles?.email}</td><td>{e.clients?.name}</td><td>{e.job_name}</td><td>{e.hours}</td><td>{e.details}</td></tr>)}</tbody></table></section>}</main></div>
}
createRoot(document.getElementById('root')).render(<App/>);
