import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient} from '@supabase/supabase-js';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import {LogOut, Plus, Download, FileText, Users, Briefcase, Clock} from 'lucide-react';
import './style.css';

const supabase = createClient(import.meta.env.VITE_SUPABASE_URL || '', import.meta.env.VITE_SUPABASE_ANON_KEY || '');
const JOBS = ['Accounts','Bookkeeping','Payroll','VAT','VIES / VAT3 Return','Tax Return','Company Secretarial','Client Communication','File / Document Sorting','Training','Meeting','Administration','Other'];

function App(){
 const [session,setSession]=useState(null); const [profile,setProfile]=useState(null); const [view,setView]=useState('entry');
 const [clients,setClients]=useState([]); const [entries,setEntries]=useState([]); const [profiles,setProfiles]=useState([]); const [loading,setLoading]=useState(true);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session); setLoading(false)}); const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(session) loadAll()},[session]);
 async function loadAll(){
  const uid=session.user.id;
  const [{data:p},{data:c},{data:e},{data:ps}] = await Promise.all([
   supabase.from('profiles').select('*').eq('id',uid).single(), supabase.from('clients').select('*').order('name'),
   supabase.from('time_entries').select('*, clients(name,hourly_rate), profiles(full_name)').order('work_date',{ascending:false}),
   supabase.from('profiles').select('*').order('full_name')]);
  setProfile(p); setClients(c||[]); setEntries(e||[]); setProfiles(ps||[]);
 }
 if(loading) return <div className="center">Loading...</div>;
 if(!session) return <Login/>;
 const isManager = ['admin','manager'].includes(profile?.role);
 return <div><header><div><h1>PTB Time Management System</h1><p>Accounting timesheet, billing and productivity dashboard</p></div><button onClick={()=>supabase.auth.signOut()}><LogOut size={16}/> Sign out</button></header>
 <nav><button className={view==='entry'?'active':''} onClick={()=>setView('entry')}><Plus size={16}/> Time Entry</button><button className={view==='staff'?'active':''} onClick={()=>setView('staff')}><Users size={16}/> Staff Summary</button><button className={view==='client'?'active':''} onClick={()=>setView('client')}><Briefcase size={16}/> Client Summary</button>{isManager&&<button className={view==='clients'?'active':''} onClick={()=>setView('clients')}>Client Admin</button>}</nav>
 <main>{view==='entry'&&<EntryForm session={session} clients={clients} refresh={loadAll}/>} {view==='staff'&&<StaffSummary entries={entries} profiles={profiles}/>} {view==='client'&&<ClientSummary entries={entries}/>} {view==='clients'&&isManager&&<ClientAdmin clients={clients} refresh={loadAll}/>}</main></div>
}
function Login(){const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[mode,setMode]=useState('signin'),[msg,setMsg]=useState(''); async function submit(e){e.preventDefault(); setMsg(''); const res= mode==='signin'? await supabase.auth.signInWithPassword({email,password}) : await supabase.auth.signUp({email,password,options:{data:{full_name:name}}}); if(res.error) setMsg(res.error.message); else setMsg(mode==='signup'?'Account created. Please check email if confirmation is enabled.':'Signed in.');} return <div className="login"><form onSubmit={submit}><h2>Secure Staff Login</h2>{mode==='signup'&&<input placeholder="Full name" value={name} onChange={e=>setName(e.target.value)} required/>}<input type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} required/><button>{mode==='signin'?'Login':'Create staff account'}</button><a onClick={()=>setMode(mode==='signin'?'signup':'signin')}>{mode==='signin'?'Create account':'Back to login'}</a><p>{msg}</p></form></div>}
function EntryForm({session,clients,refresh}){const today=new Date().toISOString().slice(0,10); const [f,setF]=useState({work_date:today,client_id:'',client_name:'',job_name:'Accounts',hours:'',billable:true,work_details:''}); const [msg,setMsg]=useState(''); async function save(e){e.preventDefault(); let client_id=f.client_id; if(!client_id&&f.client_name){const {data,error}=await supabase.from('clients').insert({name:f.client_name}).select().single(); if(error){setMsg(error.message);return} client_id=data.id;} const {error}=await supabase.from('time_entries').insert({...f, client_id, user_id:session.user.id, hours:Number(f.hours)}); if(error) setMsg(error.message); else {setMsg('Saved.'); setF({...f,hours:'',work_details:'',client_name:''}); refresh();}} return <section className="card"><h2>Add Time Entry</h2><form className="grid" onSubmit={save}><label>Date<input type="date" value={f.work_date} onChange={e=>setF({...f,work_date:e.target.value})}/></label><label>Client<select value={f.client_id} onChange={e=>setF({...f,client_id:e.target.value})}><option value="">Select or add new</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>New client<input placeholder="Only if not in list" value={f.client_name} onChange={e=>setF({...f,client_name:e.target.value,client_id:''})}/></label><label>Job<select value={f.job_name} onChange={e=>setF({...f,job_name:e.target.value})}>{JOBS.map(j=><option key={j}>{j}</option>)}</select></label><label>Hours<input type="number" step="0.25" min="0.25" value={f.hours} onChange={e=>setF({...f,hours:e.target.value})} required/></label><label>Billable<select value={f.billable?'yes':'no'} onChange={e=>setF({...f,billable:e.target.value==='yes'})}><option value="yes">Billable</option><option value="no">Non-billable</option></select></label><label className="wide">Work details<textarea value={f.work_details} onChange={e=>setF({...f,work_details:e.target.value})}/></label><button className="primary">Save Entry</button></form><p>{msg}</p></section>}
function group(entries,key){return entries.reduce((a,e)=>{const k=key(e)||'Unknown'; a[k]??=[]; a[k].push(e); return a},{})}
function StaffSummary({entries}){const rows=Object.entries(group(entries,e=>e.profiles?.full_name)).map(([name,items])=>({name,hours:sum(items),billable:sum(items.filter(i=>i.billable)),clients:[...new Set(items.map(i=>i.clients?.name).filter(Boolean))].join(', '),jobs:[...new Set(items.map(i=>i.job_name))].join(', ')})); return <Report title="Staff Summary" rows={rows} columns={['name','hours','billable','clients','jobs']} entries={entries}/>}
function ClientSummary({entries}){const rows=Object.entries(group(entries,e=>e.clients?.name)).map(([name,items])=>({name,hours:sum(items),billable:sum(items.filter(i=>i.billable)),staff:[...new Set(items.map(i=>i.profiles?.full_name).filter(Boolean))].join(', '),jobs:[...new Set(items.map(i=>i.job_name))].join(', '),billing: items.reduce((a,e)=>a+(e.billable?Number(e.hours)*(Number(e.clients?.hourly_rate)||0):0),0).toFixed(2)})); return <Report title="Client Summary" rows={rows} columns={['name','hours','billable','staff','jobs','billing']} entries={entries}/>}
function sum(items){return items.reduce((a,e)=>a+Number(e.hours||0),0).toFixed(2)}
function Report({title,rows,columns}){function csv(){const text=[columns.join(','),...rows.map(r=>columns.map(c=>'"'+String(r[c]??'').replaceAll('"','""')+'"').join(','))].join('\n'); download(text,title+'.csv','text/csv')} function pdf(){const doc=new jsPDF(); doc.text(title,14,15); autoTable(doc,{head:[columns],body:rows.map(r=>columns.map(c=>r[c]??'')),startY:22}); doc.save(title+'.pdf')} return <section className="card"><div className="toolbar"><h2>{title}</h2><button onClick={csv}><Download size={16}/> CSV</button><button onClick={pdf}><FileText size={16}/> PDF</button></div><table><thead><tr>{columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{columns.map(c=><td key={c}>{r[c]}</td>)}</tr>)}</tbody></table></section>}
function download(text,name,type){const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([text],{type})); a.download=name; a.click()}
function ClientAdmin({clients,refresh}){const [name,setName]=useState(''),[rate,setRate]=useState(''); async function add(e){e.preventDefault(); await supabase.from('clients').insert({name,hourly_rate:Number(rate||0)}); setName('');setRate('');refresh()} return <section className="card"><h2>Client Admin</h2><form className="inline" onSubmit={add}><input placeholder="Client name" value={name} onChange={e=>setName(e.target.value)} required/><input placeholder="Hourly rate" type="number" value={rate} onChange={e=>setRate(e.target.value)}/><button>Add</button></form><table><tbody>{clients.map(c=><tr key={c.id}><td>{c.name}</td><td>€{c.hourly_rate||0}/h</td></tr>)}</tbody></table></section>}
createRoot(document.getElementById('root')).render(<App/>);
